extends: common.yaml
kind: base
id: liander2024_solar_park
data:
  entity_type: solar_park
protocol:
  entity_count: 5
  ordered_entity_ids:
    - "solar_park::Within 5 kilometers of Leeuwarden_normalized"
    - "solar_park::Within 15 kilometers of Oosterwolde_normalized"
    - "solar_park::Within 15 kilometers of Zutphen_normalized"
    - "solar_park::Within 20 kilometers of Rotterdam_normalized"
    - "solar_park::Within 10 kilometers of Westwoud_normalized"
