extends: common.yaml
kind: base
id: liander2024_transformer
data:
  entity_type: transformer
pit:
  monotone_repair: isotonic
protocol:
  entity_count: 15
  ordered_entity_ids:
    - "transformer::OS Apeldoorn"
    - "transformer::OS Middenmeer"
    - "transformer::RS Grouw (Grou)"
    - "transformer::RS Wieringerwerf"
    - "transformer::OS Lelystad"
    - "transformer::RS Poederoijen"
    - "transformer::OS Tiel"
    - "transformer::OS Doetinchem"
    - "transformer::OS Oterleek"
    - "transformer::OS Nijmegen"
    - "transformer::OS Amsterdam Hemweg"
    - "transformer::RS Surhuisterveen"
    - "transformer::OS Ede"
    - "transformer::RS Roodwilligen (Duiven)"
    - "transformer::RS Minnertsga"
