extends: common.yaml
kind: base
id: liander2024_wind_park
data: {entity_type: wind_park}
protocol:
  entity_count: 5
  ordered_entity_ids:
    - "wind_park::Within Stadsregio Arnhem Nijmegen_normalized"
    - "wind_park::Within 15 kilometers of Opmeer_normalized"
    - "wind_park::Within 20 kilometers of Leeuwarden_normalized"
    - "wind_park::Within 15 kilometers of Alphen aan den Rijn_normalized"
    - "wind_park::Within 15 kilometers of Dronten_normalized"
